### PR TITLE
Use pkg-config to find libzmq

### LINKED ISSUE #181: xeus-cling has the problem finding ZeroMQ through a cmake script too
See https://github.com/QuantStack/xeus/pull/75

### PR DESCRIPTION
**Pull request by JohanMabille**
Fixes #181

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I don't understand why adding libzmq here is required (and why there is issue #181) since libzmq was not a direct dependency.

**Comment by SylvainCorlay** [comment]
A way to check would be to create a conda environment with libzmq, delete the zeromq cmake config files, and try building xeus with the latest pr merged then this one.

**Comment by JohanMabille** [comment]
Even if it is an indirect dependency, it has to be found at link. `find_package` and cmake dependency mechanism can propagate the path to the library to indirect dependencies, but I guess that it's not the case when using `pkg-config`.

I'm not sure of that last statement though, I agree that we should check that in a conda environment with xeus master installed

**Comment by SylvainCorlay** [comment]
I could check that this should not be required. Closing.

**Pull request closed without merging**
