### PR TITLE
Some formatting

### PR DESCRIPTION
**Pull request by SylvainCorlay**
- Add new xeus-cling logo to readme.
- Removing the C++17 kernel spec since not functional in our build.
- Adding a missing copyright statement and license terms
- I came across conflicts in inclusion guards when moving things to the xtl. So now, we will prefix library inclusion guards in all libraries. I propose XCPP for this one.
- Wrap `_popen / popen` with WIN32 guards.

### CODE REVIEW

**Comment by JohanMabille** [comment]
Ok for the library inclusion guards. Out of curiosity, which headers generated conflicts ?

**Comment by gouarin** [comment]
We probably need a coding style to avoid all these changes. 

Do you have one for `xtensor` ?

**Comment by SylvainCorlay** [comment]
We have been using clang-format locally to clean up repos but it does not
behave very well with certain cases so we prefer not to make it part of the
CI.

S.

**Comment by SylvainCorlay** [comment]
The first instance of conflict was XCLOSURE_HPP which was used for the
expression closure in xtensor and the new closure type header in xtl.

**Pull request merged**
