### PR TITLE
Installation instructions in the README: the libuuid conda package is required

### PR DESCRIPTION
**Pull request by nthiery**

### CODE REVIEW

**Comment by nthiery** [comment]
An alternative to this pull request would be to add libuuid as explicit dependency of xeus-cling.

**Comment by nthiery** [comment]
Oh, I forgot to mention the context: without libuuid, the xeus-C++1? kernels do a timeout upon starting them in the jupyter notebook. Here is the log:
```
[I 19:03:41.521 NotebookApp] Kernel started: d6e8e0b3-361f-444c-98db-efdeb13f6aaf
[I 19:03:44.518 NotebookApp] KernelRestarter: restarting kernel (1/5)
[I 19:03:47.529 NotebookApp] KernelRestarter: restarting kernel (2/5)
[I 19:03:50.538 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 19:03:51.638 NotebookApp] Timeout waiting for kernel_info reply from d6e8e0b3-361f-444c-98db-efdeb13f6aaf
[I 19:03:53.549 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel d6e8e0b3-361f-444c-98db-efdeb13f6aaf restarted
[W 19:03:56.558 NotebookApp] KernelRestarter: restart failed
[W 19:03:56.558 NotebookApp] Kernel d6e8e0b3-361f-444c-98db-efdeb13f6aaf died, removing from map.
ERROR:root:kernel d6e8e0b3-361f-444c-98db-efdeb13f6aaf restarted failed!
[W 19:03:56.606 NotebookApp] Kernel deleted before session
[W 19:03:56.606 NotebookApp] 410 DELETE /api/sessions/77a3e27c-bb1e-411e-8f6c-c32832668c25 (127.0.0.1) 1.99ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=xeus-cling-cpp11
```
Thanks @gouarin for the help figuring out the missing dependency.

**Comment by nthiery** [comment]
Hmm, after trying to install elsewhere, it seems it's actually not libuuid that's missing (or probably it's needed, but often provided by the OS), but rather cppzmq.

**Comment by SylvainCorlay** [comment]
cppzmq is a build-time dependency to xeus-cling but not runtime.

libuuid should only be required on linux. Alternatively, the util-linux package would do as well.

The build and run dependency list looks like this:

```yaml
build:
    - cppzmq
    - zeromq
    - cryptopp
    - util-linux  # [linux]
    - cling <0.4.0
    - xeus >=0.5.4,<0.6.0
    - pugixml
    - cxxopts
 run:
    - vc 14  # [win and py>=35]
    - zeromq
    - cryptopp
    - util-linux  # [linux]
    - cling <0.4.0
    - xeus >=0.5.4,<0.6
```

**Comment by nthiery** [comment]
Salut Sylvain,

Thanks for the feedback.

Yet, without cppzmq, the kernel times out here. Adding it resolves the problem. See attached log of an install in a fresh miniconda3 environment. The mentionned notebook uses xeus-C++11; and works smoothly on the second call to jupyter notebook.

So somehow, on my machine (Ubuntu 17.04), there is something in the cppzmq package that is currently a build time dependency.

[log.txt](https://github.com/QuantStack/xeus-cling/files/1278865/log.txt)

**Comment by SylvainCorlay** [comment]
> Yet, without cppzmq, the kernel times out here. Adding it resolves the problem. See attached log of an install in a fresh miniconda3 environment. The mentionned notebook uses xeus-C++11; and works smoothly on the second call to jupyter notebook.

Actually that is right. cppzmq is only build-time dependency for xeus itself, but in xeus-cling, it is used by the interpreted c++.

**Comment by SylvainCorlay** [comment]
It is interested how a header-only library all-of-a-sudden becomes a runtime dependency with cling.

**Comment by nthiery** [comment]
>    It is interested how a header-only library all-of-a-sudden becomes a
>    runtime dependency with cling.

Ah ah, I see; indeed, that's getting tricky!

So I assume you are going to update the conda dependencies? Would
there be a way to do regression testing for this kind of issue?

**Comment by SylvainCorlay** [comment]
@nthiery thanks for testing this at such an early stage. As you see, we are getting there.

If you also `conda install xtensor xtensor-blas -c conda-forge` and run [this example notebook](https://github.com/QuantStack/quantstack-talks/blob/master/2017-08-25-jupytercon-xeus/notebooks/xtensor.ipynb) in a C++14 notebook, you should start seeing our "numpy for C++" at play!

**Comment by SylvainCorlay** [comment]
> So I assume you are going to update the conda dependencies?

Yes!

> Would there be a way to do regression testing for this kind of issue?

Yes, although it would not be a regression test for `xeus-cling`'s code, but for the recipe.

On conda-forge, each recipe has its own repository, with some (very basic testing) and we plan on having the same for the QuantStack - specific builds that cannot be on conda-forge.

**Comment by nthiery** [comment]
On Tue, Sep 05, 2017 at 09:04:29PM +0000, Sylvain Corlay wrote:
>    [1]@nthiery thanks for testing this at such an early stage. As you see,
>    we are getting there.

You are welcome! If all goes well, you will get 350 beta testers
banging hard in creative ways in two weeks for now :-) So I very much
appreciate the quick progress!

>    If you also conda install xtensor xtensor-blas -c conda-forge and run
>    [2]this example notebook in a C++14 notebook, you should start seeing
>    our "numpy for C++" at play!

Pretty promising indeed!

It probably won't be used by my freshmen students though :-) But the
plots and widgets could come up handy when they will be ripe for
production.

**Comment by SylvainCorlay** [comment]
Because of very tight binary compatibility issues that come from cling (interpreted code must use the exact same runtime as the one used to build the compiled code), we need our own channel with our own build for a number of packages (from zeromq to cryptopp, clang, llvm and cling).

The current way (`with -c QuantStack -c conda-forge`)  is not sustainable in the long run because even if QuantStack has higher priority than conda-forge, if a package is updated faster on conda-forge, it will be picked up.

For this reason, I have experimented in the past few days on building our own "miniconda-style" self-contained distrib, with notebook, xeus-cling, xtensor, etc... Where no package would come from conda-forge, and QuantStack would be the only enabled channel.

**Comment by SylvainCorlay** [comment]
> If all goes well, you will get 350 beta testers banging hard in creative ways in two weeks for now :-) 

This is really exciting!

**Comment by SylvainCorlay** [comment]
Closing since libuuid is not required, and util-linux already provides it.

**Pull request closed without merging**
