### PR TITLE
Update xeus version

### PR DESCRIPTION
**Pull request by martinRenou**
warning

### CODE REVIEW

**Comment by martinRenou** [comment]
Is it what you had in mind @SylvainCorlay?

**Comment by SylvainCorlay** [comment]
It turns out that `ipykernel` actually creates a connection file with random ports in it:

```
[scorlay@mbp ~]$ python -m ipykernel_launcher
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-58911.json
```

**Comment by SylvainCorlay** [comment]
So we might want to do the same here, but drop the comment about `Ctrl-C`.

**Comment by martinRenou** [comment]
Oh ok :) I'll do that

**Comment by SylvainCorlay** [comment]
```json
{
  "shell_port": *,
  "iopub_port": *,
  "stdin_port": *,
  "control_port": *,
  "hb_port": *,
  "ip": "127.0.0.1",
  "key": "6142699d-0cf089726a8566d10e7ead11",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}
```

**Comment by martinRenou** [comment]
See https://github.com/QuantStack/xeus/pull/109

**Comment by martinRenou** [comment]
This PR relies on https://github.com/QuantStack/xeus/pull/109

**Comment by SylvainCorlay** [comment]
Could you take this occasion to call `xeus::blocking_input_request(` instead of locally-defined `input_request(` in `xinput.cpp`? The latter can be deleted.

**Comment by SylvainCorlay** [comment]
OK, I had to make a 0.18.1 release of xeus properly exporting the symbol on windows. Now this works.

**Comment by martinRenou** [comment]
Thanks ☺️

**Pull request merged**
