### PR TITLE
README: Fix conda env activation

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by gouarin** [comment]
@martinRenou it's not always the case (it depends on the conda version). There is still `source activate` in the conda documentation.

I will suggest mentioning the two possibilities.

**Comment by martinRenou** [comment]
> There is still source activate in the conda documentation

I see `conda activate` in the documentation: https://docs.conda.io/projects/conda/en/latest/commands.html#conda-vs-pip-vs-virtualenv-commands

Actually, I did not know `source activate` was possible. I must be too young for knowing that :P

**Comment by gouarin** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

second note

**Comment by martinRenou** [comment]
Thanks for the note, I updated my commit

**Pull request merged**
